### ISSUE TITLE
Would this be able to emulate powerquicc microcontroller?

### ISSUE THREAD

**Issue by TheFern2** [hackndev/qemu#1]
I see the TODO saying is not implemented, however code below has some macros for PowerQUICC. https://github.com/hackndev/qemu/blob/46a8f32655c61baf8063ea6f5b2b8fdbdd33d157/target-ppc/cpu.h#L158

Would it work?

**Comment by farcaller** [comment]
I think you'd be better asking in the Qemu mailing list.
